### ISSUE TITLE
Utilize property drawers

### ISSUE THREAD

**Issue by progfolio** [Manoj321/elfeed-dashboard#6]
I appreciate the simplicity of the current approach, but it might be convenient to make more use of existing Org functionality.

One idea is to use property drawers to store the keymap/action associations. This has the advantage of keeping the settings associated with each heading (instead of jumping back and forth between the "* Configuration" section).
 e.g.

```
* Basics
** Update
:PROPERTIES:
:key:      U
:action:   elfeed-dashboard-update
:END:
** Search
:PROPERTIES:
:key:      s
:action:   elfeed
:END:
* Bookmarks
** Unread
:PROPERTIES:
:key:      u
:query:    "+unread"
:END:

** Emacs
:PROPERTIES:
:key:      e
:query:    "+unread +emacs"
:END:

etc.
```

You can see how this would enable you to come up with a shorthand for queries and other types of property keywords. You could also compute the leading shortcut indicator (e.g. "[U]") and display it with an overlay.

**Comment by manojm321** [comment]
That's an interesting idea, keeping config and bookmarks/basics sections is error prone in current flow.
My only suggestion would be use text-properties instead of overlays for efficiency.

**Comment by manojm321** [comment]
One problem I see with this approach is, collapsing a headline will show 3 dots "...". Assuming all the heading will be collapsed in elfeed-dashboard-mode
```
* Basics
** [U] Unread ...
** [s] Search ...
```

Also, from quick googling hiding property drawers doesn't seem to be straightforward.
